### ISSUE TITLE
Review milestone A-1 for Mapping UI

### ISSUE THREAD

**Issue by WebDevJL** [FWAJL/FieldWorkAssistantMVC#372]
Review the code done by @danish2014

**Comment by WebDevJL** [comment]
See pull request #361

**Comment by bsaiken** [comment]
Actually, you are the assignee...

**Comment by FWAJL** [comment]
@bsaiken : let me know when you're happy with @danish2014's work so I can validate his code.

**Comment by danish2014** [comment]
@bsaiken  : I have corrected A-1 issues

**Comment by bsaiken** [comment]
I will not be able to review the work until he pushes the changes to the 
FWAJL/FieldWorkAssistantMVC feature_mapping branch.

I just checked what is there and it is not fixed.

Brian

**Comment by bsaiken** [comment]
I think we are waiting on you now.  No rush from my end - I am off to 
bed and will review tomorrow.

Brian

**Comment by FWAJL** [comment]
@bsaiken : I think @danish2014 committed his work.
@danish2014 : since you are a contributor to https://github.com/FWAJL/FieldWorkAssistantMVC, please push the commit to https://github.com/FWAJL/FieldWorkAssistantMVC on the feature_mapping branch. It will avoid a pull request. Plus, @bsaiken wants to have it on our repository, not on your fork.

Thank you.

**Comment by FWAJL** [comment]
@danish2014 : please read [this] (https://github.com/FWAJL/FieldWorkAssistantMVC/wiki/4.Use-the-repository-with-Git) before committing your work properly. It'll avoid you troubles :)

**Comment by bsaiken** [comment]
Hi Jeremie,

I was able to clone the forked branch and review the revised mapping 
work. The front end for Milestone A-1 now displays correctly. Please 
review the back-end code for conformance asap, then we can move forward. 
  I will release payment once you are satisfied the code is acceptable.

Brian

**Comment by FWAJL** [comment]
See my first comments here: https://docs.google.com/document/d/1o1YfriWqDpzH6ODv4obhQJlvvEJMj2AJ4Q-HF8y_-PQ (I'm not done yet).

**Comment by bsaiken** [comment]
Have you sent these comments to Danish?  You need to do so right away.

Brian

**Comment by danish2014** [comment]
@bsaiken I got the comments
I am working on it. I will make the necessary changes soon.

**Comment by FWAJL** [comment]
@bsaiken: yes. When I use @mention, he receives git notifications and I set
the sharing to "Anyone can view with the link".

--
Jérémie Litzler

**Comment by bsaiken** [comment]
Yes, communication protocol will be on the agenda.  One of my emails to 
you accidentally went up on eLance and it contained info I did not want 
Danish to see.  grrr...

Brian

**Comment by danish2014** [comment]
I have pushed the changes

**Comment by FWAJL** [comment]
@danish2014 : 

I'm sorry to insist but please follow the instructions when pushing code.
The commit comment must be: `git commit -m "Issue #[IssueId]" -m "Some additional message if you need"`

I will review the updates.
Thank you.

**Comment by FWAJL** [comment]
@danish2014 : none of the items listed in the required updates have been done in this commit (5c24562cb46a76e8efa0091d52e3d8fb3828c168).

Have you forgotten to push some code?

Thank you.

**Comment by danish2014** [comment]
What is the list of updates?

**Comment by danish2014** [comment]
ok, you mean the errors you listed in doc?

**Comment by FWAJL** [comment]
@danish2014 : see my first comments here: https://docs.google.com/document/d/1o1YfriWqDpzH6ODv4obhQJlvvEJMj2AJ4Q-HF8y_-PQ (I'm not done yet).

**Comment by FWAJL** [comment]
@danish2014 : my list is complete. I didn't add new items to the 13 points. Are you having troubles to process some of them?

**Comment by WebDevJL** [comment]
Reviewing the code and updating the comments list.
